### ISSUE TITLE
Error in extract_traces function 

### ISSUE THREAD

**Issue by mwahbeh** [LieberInstitute/CaPTure#2]
Brace indexing is not supported for variables of this type.

Error in extract_traces (line 5)
filename1 = strrep(Dfilename, old{df}, new{df});

**Comment by madhavitippani** [comment]
`old` and `new` inputs to the function should be given as cell array like below
old = {'G.mat'}; 
new = {'R_ROI_info_4.mat'};
which was instead given as text inputs like below
old = 'G.mat';
new = 'R_ROI_info_4.mat';

which was causing the error
